README.md
Fiz algumas modificações, vejam se ajuda :smile:
=> Update informations README

CONDUTA.md, README.md, issue_template.md, mentores/README.md, mentores/mentor_template.md, mentores/perfis/andrea_zambrana.md, mentores/responsibility.md, pupilos/pupilo_template.md
Criando perfil para a mentora Andréa Zambrana
=> Perfil mentora Andréa Zambrana

mentores/perfis/dorian_neto.md, pupilos/perfis/AlexBarazal.md, pupilos/perfis/caio.md
Corrigi alguns links quebrados e aproveitei pra dar uma atualizada no perfil :P
=> Correções de links (mentores/pupilos)

mentores/README.md, mentores/perfis/fernando_moreira.md
=> Add mentor profile

pupilos/perfis/MarceloHenrique.md
Meu Perfil @woliveiras, @jessuircleydson
=> Meu Perfil

mentores/README.md, mentores/perfis/wesley_queiroz.md
=> Adicionando mentor Wésley Queiroz

pupilos/README.md, pupilos/perfis/MarcioAlves.md
=> Adicionando perfil no pupilos

mentores/perfis/wesley_queiroz.md
Pupilos Marcio, Marcos e Raul adicionados ao perfil do mentor Wésley Queiroz.
=> Pupilos no perfil de Wésley

pupilos/README.md, pupilos/perfis/GabrielleDias.md
=> Adicionando perfil de pupilo Gabrielle Dias

mentores/perfis/wesley_queiroz.md
Adicionando nova pupila Gabrielle Dias ao perfil.
Adicionando Slack e Discord aos links de contato.
=> Adicionando pupila

mentores/perfis/matheus_marsiglio.md
Added Rogerio Moura as "pupilo"
=> Update mentor Matheus Marsiglio profile

mentores/perfis/andrea_zambrana.md, pupilos/README.md, pupilos/perfis/laryro.md
Sou pupila da Andrea Zambrana e estou adicionando meu perfil :smiley:
=> Adiciona nova pupila - Laryssa Rocha

mentores/README.md, mentores/perfis/danilo_vaz.md
=> Adiciona Mentor Danilo Vaz

pupilos/README.md, pupilos/perfis/hugo_almeida.md
=> Adiciona Pupilo Hugo Almeida

mentores/README.md, mentores/perfis/raymonsanches.md
=> Adicionando Ramon Sanches como Mentor

mentores/perfis/abner_alves.md
Add my profile without pupilos bolados os quais irei ajudar
=> Add my profile abner_alves

pupilos/README.md, pupilos/perfis/YuriBrunetto.md
=> Adiciona Yuri Brunetto como pupilo

mentores/README.md, mentores/perfis/wagner_santos.md
Criando perfil do mentor e inserindo na lista de mentores.
=> Inserindo mentor

pupilos/Eduardo S. de Araujo
Mentor(a) responsável por mim
Fernando Moreira 
https://github.com/training-center/mentoria/blob/master/mentores/perfis/fernando_moreira.md
Meu Nome
Eduardo S. de Araujo
Qual meu sonho na carreira?
- Ter maior autonomia na criação de sites, não só desenhando, mas "montando" os layouts com HTML, CSS e Javascript.
- Trabalhar com jogos. 
Alguns links para me conhecer melhor
https://www.facebook.com/eduardo.s.de.araujo
https://www.linkedin.com/in/edusaraujo
=> Create Eduardo S. de Araujo

mentores/README.md, mentores/perfis/alexjunior012.md
Criei meu perfil e atualizei a listagem de mentores.
=> Inclusão do mentor Alex Junior

pupilos/README.md, pupilos/perfis/lucas_gabriel.md
=> Adiciona Pupilo Lucas Gabriel

mentores/README.md, mentores/perfis/lucas_henrique.md
=> Adiciona Mentor Lucas Henrique?

mentores/README.md, mentores/perfis/guilhermepontes.md
=> Add Guilherme as FullStack mentor

mentores/perfis/lucas_henrique.md
=> Adicionado perfil

mentores/perfis/felipe_uliana
Submitting the mentor's profile.
=> Felpe Uliana mentor profile

mentores/README.md, mentores/perfis/diego_ponciano.md
Quero ajudar como mentor de desenvolvimento back-end.
=> Perfil do Diego Ponciano.

mentores/perfis/wendell_adriel.md
@woliveiras atualizei meu perfil com o último pupilo meu e os links para os perfis dos que faltavam.
=> updated profile

pupilos/README.md, pupilos/perfis/FelipeAcelino.md
Create FelipeAcelino.md
Update README.md
=> Criação de Perfil

mentores/perfis/lucas_henrique.md
Adicionado Gustavo César Domingos Siqueira na lista de pupilos !
=> added pupilo

pupilos/README.md, pupilos/perfis/AugustoAlmeida.md
Adicionei meu perfil nos pupilos!
=> Atualizando perfis de pupilos

mentores/perfis/alexjunior012.md, pupilos/README.md, pupilos/perfis/RomarioCCoimbra.md
Atualizei o meu perfil e criei o perfil do meu pupilo Romário Coimbra.
=> issue nº233 - atualização do perfil do mentor e do pupilo

pupilos/perfis/OsmarVillalba.md
=> new member

pupilos/perfis/paulopereiradosanjos
Conforme orientação do projeto, segue PR do meu perfil de pupilo.
=> Criando perfil de pupilo

pupilos/README.md, pupilos/perfis/LeonanMachado.md
Adicionar meu perfil como pupilo
=> Add perfil leonantvrs

pupilos/README.md, pupilos/perfis/WilliamCorrea.md
=> Wilcorrea new profile pupil

pupilos/README.md, pupilos/perfis/danielsimaodasilva.md
Segue meu perfil como pupilo @woliveiras
@vinicius73 quando o PR estiver aceito pode add no seu perfil o/
=> Added Daniel Simao da Silva profile as pupil

pupilos/README.md, pupilos/perfis/JulianoPadilha.md
=> Juliano Padilha

pupilos/README.md, pupilos/perfis/AdeonirKohl.md
=> Adicionado perfil de pupilo a atualizado readme

pupilos/perfis/thivieiratav.md
=> thivieiratav.md

mentores/README.md, mentores/perfis/abner_alves.md, pupilos/perfis/PedroGermano.md
Pedro Germano aren't talking with me anymore.
=> Remove Pedro Germano as Abner's pupil and edit Abner's Status

pupilos/perfis/rpaggi.md
Estou em busca de um novo mentor...
=> Atualizando mentor Ronaldo Paggi

pupilos/README.md, pupilos/perfis/mayarapimentel.md
Falei com o Wilson Campos, e ele aceitou que eu fosse sua pupila em dev front end.
=> Pupila Dev Front End

pupilos/perfis/rafaelmartinsja
Add - Meu profile é mais de front-end com layout, interface...E o que me vejo fazendo melhor!
=> rafaelmartinsja

pupilos/perfis/rafaelmartinsja.md
Add - Wagner Santos como mentor por conta do seu conhecimento de Front-End é a área que eu preciso focar mais.
=> Add Mentor Wagner Santos

pupilos/perfis/JamileLima.md
Add novo perfil da Pupila Jamile Lima
=> Add profile of new Pupila: Jamile Lima

pupilos/perfis/vicentimartins.md
Por falta de comunicação, com meu antigo mentor, o @giovannicruz97 me aceitou como pupilo.
=> Mudança de mentor, e acrescimo de alguns contatos.

mentores/perfis/luiz_paulof.md
=> Atualização de links do meu perfil

pupilos/README.md, pupilos/perfis/AndersonNascimento.md
Adiciona perfil pupilo Anderson Nascimento
=> Adiciona perfil pupilo Anderson Nascimento

mentores/README.md
No momento estou com 3 pupilos: @theandersonn, @santosluiz e um que ainda não está no mentoria.
=> Atualização de disponibilidade

mentores/README.md
Mentoria com 2 pupilos atualmente.
=> Bloqueando perfil para novos pupilos

mentores/README.md, mentores/perfis/danilo_vaz.md
=> Update mentor's profile info

pupilos/README.md, pupilos/perfis/jonatan_vianna.md
Adicionei o perfil de pupilo
Abç
Jonatan
=> Criação perfil Pupilo

pupilos/README.md, pupilos/perfis/SafireLauene.md
=> Add Safire Lauene

mentores/perfis/erikpatekoski.md
=> Add erikpatekoski.md

profiles/pupils/README.md, profiles/pupils/profiles/leonardofaria.md
Pupilo Leonardo de Souza Faria
=> Create perfil pupilo

profiles/mentors/README.md
Estou sem computador temporariamente para acompanhar os novos pupilos, espero em breve abrir novamente.
=> Não estou aceitando momentaneamente novos pupilos

profiles/pupils/README.md
=> Corrigido perfil com link errado

profiles/mentors/profiles/kiver.md
=> Adicionado pupilo

profiles/mentors/README.md, profiles/mentors/profiles/diogo_cercilio.md
=> Adicionando profile mentor Diogo Cercilio

profiles/pupils/profiles/GabrielBrito.md
=> Updating Gabriel Brito profile

README.md, profiles/mentors/responsibility.md
=> Corrigindo os links de lista de pupilos e template de pupilos

profiles/mentors/README.md, profiles/mentors/profiles/ademilson_tonato.md
Ainda há alguns pupilos em contato comigo que provavelmente farão parte do meu time, todavia por hora me limito a esses para que eu possa trazer maior qualidade e dar mais atenção aos que até então me escolheram =)
=> Adicionar pupilos e alterar limitar recebimento de pupilos

profiles/pupils/README.md, profiles/pupils/profiles/CelsoLopes.md
Adicionando para iniciar como pupilo.
=> Adicionando meu perfil como pupilo

README.md
Corrige o trecho de texto _"ema área de atuação (ou mais) com"_ onde foi escrito **ema** ao invés de **em uma**.
=> Correção ortográfica.

profiles/pupils/README.md
Novo pupilo adicionado - Eric Madureira
=> Update lista de pupilos

profiles/pupils/profiles/AndreTeles.md
=> Created AndreTeles.md

profiles/mentors/README.md, profiles/mentors/profiles/luiz_felipe_limeira.md
Enrico e Rafael adicionados como pupilos
=> Pupilos adicionados

profiles/pupils/README.md, profiles/pupils/profiles/LeonardoMaturano.md
Inclusão do perfil de pupilo de Leonardo Maturano
=> Inclusão do perfil de pupilo

profiles/mentors/profiles/luiz_felipe_limeira.md
Leonardo Maturano adicionado como pupilo.
=> Inclusão de pupilo

profiles/pupils/README.md, profiles/pupils/profiles/AndersonAltissimo.md
Adicionado o meu perfil de Pupilo
=> Add Perfil de Pupilo

profiles/mentors/profiles/ademilson_tonato.md, profiles/pupils/profiles/FernandoCosta.md
Good morning,
Como havia conversado com o @nandocosta, estou atualizando meu perfil, pois no momento ele não dispõem de tempo necessário para a mentoria.
Assim que ele tiver disponibilidade, voltará a procurar por mentores (por isso deixei o perfil dele ainda disponível).
/cc @training-center/mentors
=> Atualizar meu perfil enquanto mentor e o perfil de um pupilo

README.md
Since I'm transferring all my courses to Udemy, it makes sense to update this link here.
=> Updating Git Course Link

profiles/mentors/profiles/anderson_juhasc.md, profiles/pupils/README.md, profiles/pupils/profiles/MuriloMarchesi.md
Adicionando meu perfil - Murilo Marchesi
=> adicionando meu perfil!

profiles/mentors/profiles/lucas_santos.md, profiles/pupils/README.md, profiles/pupils/profiles/FelipeRSAbbud.md
Espero que esteja tudo certo  :+1:
=> Adicionando o perfil de pupilo Felipe R S Abbud

README.md
Mesmo link quebrado corrigido em: https://github.com/training-center/sobre/pull/18
=> Correção de Link

profiles/mentors/README.md, profiles/mentors/profiles/matheus_fidelis.md
Segue meu perfil para análise.
=> To afim de ser um novo mentor :) 

profiles/mentors/README.md, profiles/mentors/profiles/kirmayr_tomaz.md
Oi pessoal, gostaria de  colocar a disposição mentoria para node.js back-end XD
=> Mentoria Kirmayr Tomaz Backend Nodejs

profiles/mentors/README.md, profiles/mentors/profiles/cassio_pereira.md
=> Perfil cassio adicionado

profiles/mentors/profiles/luiz_fernando.md, profiles/mentors/profiles/wilson_campos.md, profiles/pupils/profiles/AdeonirKohl.md
Tentei contato com meu mentor por diversas vezes e, como não tive resposta, estou aproveitando a oportunidade de trabalhar sob uma nova mentoria.
=> Atualizando perfil de pupilo

profiles/mentors/README.md, profiles/mentors/profiles/gustavo_cardoso.md
I just added my profile as a new mentor. Thanks!!!
=> Add mentor Gustavo Cardoso

profiles/mentors/README.md, profiles/mentors/profiles/danilo_agostinho.md
=> Adiciona perfil Danilo Agostinho

profiles/pupils/profiles/RamonFrancisco.md
=> Update new mentor

profiles/mentors/README.md, profiles/mentors/profiles/vinicius_torves.md
=> add Mentor Vinicius Torves

profiles/mentors/profiles/ademilson_tonato.md, profiles/pupils/profiles/AmonLucas.md, profiles/pupils/profiles/RichardManzoli.md, profiles/pupils/profiles/WerberthVinicius.md
Olá queridos,
Tomei a liberdade de atualizar o perfil dos pupilos que eu já mentorei, além também de ter criado uma _subcategoria_ no meu perfil para descrever quais pessoas já fizeram parte da minha mentoria ;)
=> Atualizar meu perfil enquanto mentor

profiles/mentors/profiles/dorian_neto.md
Atualização da minha descrição, links e inclusão de novo pupilo :)
=> Atualização do perfil do mentor: Dorian Neto

profiles/pupils/README.md, profiles/pupils/profiles/AndreAlmeida.md
=> Perfil do pupilo Andre Almeida criado

profiles/pupils/profiles/MayronThomasCeccon.md
> We've detected the file encoding as ISO-8859-1. When you commit changes we will transcode it to UTF-8.
/cc @training-center/moderators
=> Correção de encoding no perfil

profiles/mentors/profiles/diegomalone.md
Corrigindo case do link do perfil de pupilo.
=> Corrigindo link de perfil de pupilo

profiles/pupils/README.md, profiles/pupils/profiles/HenriqueRodrigues.md
=> Pupilo Henrique Rodrigues

profiles/mentors/README.md, profiles/mentors/profiles/guilherme-augusto-henschel.md
Conheci a iniciativa do Training Center e gostei muito da ideia. Espero poder contribuir com a comunidade e logo ter alguns pupilos 🙌 
Li o código de conduta e estou de acordo 👍
=> Adicionando perfil de Mentor

profiles/mentors/README.md, profiles/mentors/profiles/guilherme-augusto-henschel.md
Ficou faltando substituir uma tag com meu nome no meu perfil e coloquei meu perfil como Full Stack.
=> Atualização de dados no Perfil e na Lista de Mentores

profiles/mentors/README.md, profiles/mentors/profiles/reinaldo_oliveira.md
Boa tarde pessoal,
Estou a disposição caso precisem de mais alguma informação.
Abraços.
=> Adicionando mentor Reinaldo Oliveira

profiles/pupils/profiles/lisandra_rocha.md
Normalizei o link em forma de lista apenas
=> Atualização para normalização de arquivo

profiles/pupils/README.md, profiles/pupils/profiles/LucasSilva.md
Olá!
Virei pupilo do Felipe Fialho.
Segue o PR.
Abs. :smiley:
=> Adicionando meu perfil

profiles/pupils/README.md, profiles/pupils/profiles/DanielDeJesusOliveira.md
My profile as Android development pupil
=> Added my profile as pupil

profiles/pupils/pupil_template.md
Corrigido o template para não gerar mais dúvidas
=> Adicionado links em forma de lista no template

profiles/pupils/profiles/AllanSantos.md
=> Adicionados links em forma de lista

profiles/pupils/README.md, profiles/pupils/profiles/RaquelAFLuz.md
A PR original #727 estava com conflitos muito extensos, achei melhor criar uma nova com as alterações
=> Adiciona pupila Raquel Luz

profiles/mentors/README.md, profiles/mentors/profiles/henrique_maich.md
Adicionando arquivos para me tornar um dos Mentores do Training Center
=> Adicionando Mentoria - Henrique Maich

profiles/mentors/profiles/diegomalone.md, profiles/pupils/profiles/DanielDeJesusOliveira.md, profiles/pupils/profiles/MatheusAraujo.md, profiles/pupils/profiles/elton_coelho.md, profiles/pupils/profiles/gabrielsouzaa.md, profiles/pupils/profiles/lucascapistrano.md
Removendo pupilos que já saíram do projeto a tempos e o que saiu agora. Adicionando o que estava faltando no meu perfil.
=> Atualizando minha lista de pupilos

profiles/mentors/profiles/luiz_tanure.md
nao encontrei o profile deles, vou pedir para criarem
=> Atualiza lista de pupilos

profiles/mentors/profiles/henrique_maich.md
Conforme solicitado estou adicionando meu email e skills
=> Adicionando Email e Skills

profiles/pupils/profiles/matheus_mazeto.md
Add info: para melhor entendimento do perfil e para facilitar contatos futuros.
=> Add informações no perfil.

profiles/pupils/profiles/WaldreySouzaSilva.md
E-mail adicionado na lista do perfil.
=> add email list

profiles/mentors/profiles/william_w_oliveira.md
Conforme foi solicitado (#781), segue adição do meu nome e organização por ordem alfabética nos nomes dos pupilos.
=> Solicitação de alteração

profiles/mentors/README.md, profiles/mentors/profiles/felipe_orlando.md
=> Add new mentor

profiles/pupils/profiles/AllanSantos.md
Adicionei meu email ao perfil e o link para o perfil do tutor estava quebrado e foi fixado.
=> Insere email e atualiza link tutor

profiles/mentors/README.md, profiles/mentors/profiles/dener_rocha.md
Estou a disposição para ajudar quem está iniciando e precisa de um norte a seguir.
=> Informações para início como mentor

profiles/pupils/README.md, profiles/pupils/profiles/ThomasJoaquini.md
=> Add Thomas Joaquini as pupil

profiles/mentors/README.md, profiles/mentors/profiles/leandro_bighetti.md
* Added new file for Leandro as mentor on profiles folder
* Added Leandro on the mentor README.md relevant sections
* Re-ordered some sections to be alphabetic
=> Adding Leandro Bighetti as a mentor, improving mentor README.md

profiles/pupils/README.md, profiles/pupils/profiles/felipe_simoes.md
Pupilo do @lbighetti em Elixir
=> Adding pupil Felipe Simoes

profiles/mentors/profiles/jessuir_cleydson.md
=> Atualizando perfil

profiles/pupils/profiles/TuannyRuiz.md
Hey @training-center/mentors, aceitei um _PR_ sem estar no formato correto os links, agora segue a correção!
=> Adicionar lista aos links do perfil

profiles/mentors/profiles/jonathan_lamim.md
Atualização das informações do meu perfil
=> Atualização do meu perfil

profiles/mentors/README.md, profiles/mentors/profiles/william_correa.md
Olá pessoal, 
meu nome é William Correa e estou declarando que estou disposto a participar do projeto como mentor.
Eu li o [código de conduta]( https://github.com/training-center/mentoria/blob/master/admin/CONDUTA.md) e estou plenamente de acordo com ele. Ressalto que acompanho o projeto a algum tempo e que já estou no Slack.
Aguardo orientações quanto aos procedimentos vindouros.
Abraços e parabéns pelo projeto
=> Adicionando William Correa como mentor do Training Center

profiles/mentors/README.md, profiles/mentors/profiles/renanbirlem.md
Adiciona mentor fullstack Renan Birlem
=> Add renanbirlem to the fullstack mentoring list

profiles/mentors/responsibility.md
Removendo Referencia ao Telegram e trocando para referencia ao Slack.
Resolvendo issue #850
=> #850: Removendo Referencia ao Telegram

profiles/mentors/profiles/henrique_maich.md
Linkando perfil do mentorado no meu perfil
Também fiz pequenas correções e atualizações do meu perfil.
=> Adicionando mentorado e atualizando perfil

profiles/mentors/README.md, profiles/mentors/profiles/leocavalcante.md
Fiquei em dúvida com relação a organização das seções em mentoria.
Algumas são específicas tipo .NET, Java e Python, outras são mais genéricas como Back-end e ainda tem a Desenvolvimento web em geral.
Também não soube onde poderia encaixar React Native.
Fica a sugestão aí de organizar os títulos dessas áreas, posso ajudar se for o caso.
Abs
=> Adiciona mentor: Leo Cavalcante

profiles/pupils/README.md, profiles/pupils/profiles/FabioMoreira.md
Inclusão do arquivo de perfil e o link do mesmo no README.md da pasta pupils.
=> Inclusão de perfil de mentorado

profiles/mentors/README.md, profiles/mentors/profiles/carlos_augusto.md
Olá, estou me candidatando para a vaga de Mentor.
*Alterações.
Adicionado o meu perfil.
Ajustado o redirecionamento do READMe para o meu perfil.
Ajustado o PHP pois tinham 2 iguais.
=> Novo mentor carlos_augusto

profiles/pupils/profiles/thaysa_santos.md
Atualizando pasta para me incluir(Thaysa Mara M. Santos)
=> Add thaysa_santos.md

profiles/mentors/profiles/antonio_ladeia.md, profiles/pupils/README.md, profiles/pupils/profiles/DavidAllysson.md
Adicionando meu perfil de pupilo, meu nome na lista de mentorados e meu nome na lista de pupilos do meu mentor.
=> Adicionando meu perfil de pupilo

profiles/mentors/profiles/henrique_maich.md
Adicionando perfil do mentorado Leonardo Bressan ao meu perfil.
=> Linkando perfil mentorado ao meu perfil

profiles/mentors/README.md, profiles/mentors/profiles/igorAndrade.md
Gostaria de me inscrever como mentor
Obrigado
=> Interesse em ser um novo mentor

profiles/mentors/README.md, profiles/mentors/profiles/rodolfo_mendes.md
Declaro que li e concordo com as [Regras de Conduta](https://github.com/training-center/mentoria#regras-de-conduta) de mentoria.
=> Inclusão de Rodolfo Mendes para mentoria Java

profiles/mentors/profiles/raphael_pacheco.md
=> raphael_pacheco.md

profiles/mentors/README.md, profiles/mentors/gionaufal.md, profiles/mentors/profiles/gionaufal.md
Gostaria de me incluir como mentor, e confirmo que li e concordo com o código de conduta e as regras de mentoria.
=> Add Giovanni Naufal as mentor

profiles/pupils/README.md, profiles/pupils/profiles/GuilhermeThales.md
Adicionando meu perfil (Guilherme Thales) a lista de mentorados, colocando meus dados e o Matheus Castiglioni como meu mentor.
=> Adicionando perfil Guilherme Thales a lista de mentorados

profiles/mentors/profiles/diegomalone.md, profiles/pupils/profiles/DanielDeJesusOliveira.md, profiles/pupils/profiles/elton_coelho.md
Removendo pupilos que não estão mais ativos nos estudos.
=> Removendo pupilos

profiles/mentors/profiles/matheus_castiglioni.md
Adicionei Medium e Instagram como redes sociais e o Guilherme Thales como pupílo.
=> Atualização no meu perfil com novas redes sociais e pupílos

profiles/mentors/profiles/lucas_santos.md
Alguns ainda não tem perfil, estou pedindo a criação
=> Atualizando lista de pupilos

profiles/mentors/profiles/khaue_viana.md
Eu já mentorava o João, só faltou atualizar o perfil ;)
=> Atualização perfil

profiles/mentors/README.md
ai legal isso ai de deixar o pessoal mais novato contribuir com coisa básica
=> limpeza da lista de mentores(as)

README.md
@woliveiras adicionei os nomes dos 3 que deram resposta que vão ajudar. O @engaugusto  também tava no tópico mas ele não respondeu se *está dentro*.
Avalia ai e já aprova se estiver ok.
=> Moderadores adicionados

profiles/mentors/README.md, profiles/mentors/profiles/ricardo_tulio.md
Este PR adiciona meu perfil como mentor. Já preenchi o formulário de mentores, estou no slack e li o código de conduta.
=> Adiciona perfil de mentor de Ricardo Tulio

profiles/mentors/README.md, profiles/mentors/profiles/bruno_matuk.md
Adicionando meu perfil de mentor
=> Perfil de Mentor - Bruno Matuk

mentors-list.md
=> Adding my name in mentors list

mentors-list.md
*Adicionar novo(a) mentora a lista
* Foi adicionada a lista de mentores Juliana Dias Santos e Silva
* Checagem visual
=> Add mentor Juliana Dias Santos e Silva to list

mentors-list.md
- Adicionar Bruno Matuk como mentor
- Novo mentor respeitando a ordem alfabética
- Checagem visual
=> Add mentor Bruno Matuk

mentors-list.md
Me incluir na lista de mentores
A lista de mentores agora conta com os meus dados e está ordenada alfabeticamente
Verificar os dados e contato.
=> Atualização da lista de mentores

mentors-list.md
Adicionar-me como mentor.
A lista de mentores
Verificar se a lista permanece com os mentores antigos acrescido de mim seguindo o template.
=> Add jcserracampos as mentor

mentors-list.md
Adicionar-me na lista de mentores
Uma linha com minhas informações foi adicionada no final do arquivo
Não tenho certeza 😅
=> Adiciona Alexandre Gaigalas na lista de mentores

mentors-list.md
Adicionar meu contato a lista de mentores
=> Add Lucas Ricoy

mentors-list.md
Adicionando meu perfil como mentora
Nova linha ao final
=> Add liviagabos

mentors-list.md
Adicionar Glauber Sampaio como mentor
mentors-list.md
Verificar se a linha 16 atende aos critérios definidos no .github/mentor-list.template.md
=> Adicionando Glauber Sampaio como mentor

mentors-list.md
=> adds omarkdev in mentor-list

mentors-list.md
Nesse PR me adiciono como mentora. :)
=> Add Ana Paula Gomes

mentors-list.md
=> Add snowflake

mentors-list.md
Me adicionar na lista de mentores. 
Adicionei uma nova linha com os meus dados no topo da lista.
Verificar se os dados estão condizentes com o que foi proposto e se não quebrei a tabela.
=> Nova mentora na lista de mentores

mentors-list.md
Tirei meu contato (por enquanto) :D
=> Mari snowzada com 3 mentorados :)

mentors-list.md
Gostei da ideia do projeto e desejo participar como mentor.
Adicionar-me no projeto.
Inclusão do meu contato.
Verificar que meu novo foi incluido corretamente como mostra o template.
=> Novo mentor

mentors-list.md
Adicionar meu nome na lista de mentores.
Adicionei uma linha no topo da lista.
Verificar se eu não quebrei o markdown inteiro :P
=> Me adiciona como mentora (:

mentors-list.md
Congelando contato por já ter atingido o limite de pessoas sendo mentoradas.
=> Snowzando lricoy

mentors-list.md
Adicionar meu nome na lista de mentores.
Adição de linha na tabela `mentors-list`.
=> Add Bruno Alano

mentors-list.md
Adicionar chicocvenancio a mentors-list.md
mentors-list.md
=> Adicionar chicocvenancio a mentors-list.md

mentors-list.md
=> Add Marcelo Duarte Trevisani

mentors-list.md
Adicionado Giovanni Cruz à lista de mentores
Adicionado mentor a lista de mentores
=> Adicionado Giovanni Cruz à lista de mentores

README.md
Ajustar o rodapé (CT -> Training Center
README.md
verificar se no rodape do arquivo houve a alteração de 'CT' para 'Training Center'
=> Ajustando rodape

mentors-list.md
Atualizar o status de disponibilidade de mentoria de Glauber Sampaio
mentors-list.md
Verificar se existe o snowflake na coluna 'contato' do mentor Glauber Sampaio
=> Congelando mentoria de Glauber

mentors-list.md
Adicionar Vinícius Alonso à lista de mentores.
Adicionando mentor à lista de mentores.
Verificar padrão do template de mentores (as).
=> Add Vinícius Alonso as mentor

mentors-list.md
Adicionar Elâine Okada a lista de mentores
Arquivo mentors-list.md
Conferir o padrão do [template](./.github/mentor-list.template.md)
=> Add Elaine Okada as mentor

mentors-list.md
* Add snowflake to Juliana Dias
* Change contact to icon :snowflake: 
* n/d
=> Add snowflake to Juliana Dias

mentors-list.md
Add snowFlake to Caio Alcantara
=> Add snowFlake to Caio Alcantara

mentors-list.md
Adicionar Claudson Oliveira a lista de mentores. 
Arquivo mentors-list.md.
Conferir o padrão do [template](mentor-list.template.md).
=> Add Claudson Oliveira as mentor

mentors-list.md
Incluir-me na lista de mentores
Adicionada uma linha no início da tabela
Verificar se as informações publicadas estão de acordo com os requisitos
=> Add Júlio Fortunato as mentor

mentors-list.md
Adicionar o ❄️ no meu contato, visto que já estou com o máximo de mentorados que consigo acompanhar
Coluna da minha informação de contato
Verificar se a tabela não foi quebrada
=> Freezing my contact for now

mentors-list.md
Adicionar snowflake na minha mentoria.
Foi adicionado um snowflake no meu contato.
Verificar se o snowflake foi inserido corretamente e se não quebrei o layout da tabela.
=> Add snowflake to a mentor

mentors-list.md
Adicionando :snowflake: em Claudson Oliveira. Por enquanto quero focar em uma pessoa e ver como o mentoria funciona 😄  . 
:snowflake: adicionado em Claudson Oliveira
Olhar arquivo [template](mentor-list.template.md) 
=> Adicionando :snowflake: em Claudson Oliveira

mentors-list.md
Adicionando snowflake em Marcos Felipe. Por enquanto quero focar em uma pessoa para poder me organizar melhor.
:snowflake: em Marcos Felipe
Olhar [mentor-list.md](mentor-list.md)
=> Snowflake marcos

mentors-list.md
Disponibilizar-me como mentor sobre front end, angular e testes automatizados.
Adicionado uma linha ao fim da tabela de mentores.
=> Add Guilherme Gois as mentor

mentors-list.md
Inclusão da minha pessoa como mentor Fullstack
Incluí meus dados
=> Inclusão Mentoria

mentors-list.md
Inserir floco de neve no meu nome na lista.
Retirada do meu user e alteração para :snowflake:
Ver se o ❄️ aparece no lugar do meu contato.
=> Inserindo floco de neve no meu nome na lista

mentors-list.md
Me incluindo na lista de mentores
=> Incluir @fpg1503 na lista

mentors-list.md
Me incluindo na lista de mentores 😸
=> Incluindo na lista de mentores

mentors-list.md
=> Inclusão na lista de mentores

mentors-list.md
=> +1 lista de mentores

mentors-list.md
Adicionar @souenzzo na lista de mentor
A lista de mentores
Conferir preview da lista de mentores
=> Incluindo @souenzzo na lista de mentores

mentors-list.md
Adição do meu nome como mentor
Adição do meu nome, background e contato
Procurar por Ingo Hoffmann
=> Adição de Ingo Hoffmann

mentors-list.md
Adicionar Ana Coimbra como mentora
Lista de mentores
=> add Ana Coimbra

.github/mentor-list.template.md, mentors-list.md
Melhorar mais os meios de contato da lista de mentores.
* Agora vai mostrar o nome do site ao invés do `@user_name`
* @woliveiras passa o olho na lista e no template quando puder.
=> Mais melhorias na lista de mentores

mentors-list.md
Incluir meu nome na lista de mentoria
Mentors-list.md
Meu nome deve estar em primeiro lugar no ultimo PR.
=> Fill my name in mentorslist

mentors-list.md
Add snowflake Bruno Matuk
Snowflake - Bruno Matuk
=> Add snowflake Bruno Matuk

mentors-list.md
Me adicionar a lista de mentores
Lista de Mentores
=> Update mentors-list.md Adding @davibusanello

mentors-list.md
Adicionar um link para mais infos, já que estou recebendo um fluxo grande de mensagens parecidas.
Coloquei um `[info]` após a lista de tópicos.
O link funciona e `[info]` aparece?
=> Add link to more info about my mentoring

mentors-list.md
Incluir meu nome na lista de mentoria.   
Mentors-list.md  
Meu nome deve estar em primeiro lugar no ultimo PR.  
=> add canofre

mentors-list.md
Adicionar meus dados na mentoria
Lista de mentores
=> Add myself to mentors list :tada:

mentors-list.md
Adicinar Bruno C. Couto na lista de mentores.
=> Add Bruno C. Couto to mentors-list file

mentors-list.md
Criei uma conta no telegram para facilitar um pouco.
=> Inclusão do meu Telegram

mentors-list.md
Congelar meu contato temporariamente
:snowflake:
=> Add :snowflake: to my name

mentors-list.md
Eu ja estou mentorando desde antes da mudança. Estou mandando o PR para atualizar o perfil no padrão.
Atualizado o modelo.
Ja tenho perfil do modelo antigo.
=> Perfil mentor Gabriel

mentors-list.md
Me adicionar à lista de mentores
Adicionei uma linha na tabela com meus dados
=> Add Aline Pêgas to the mentors list

mentors-list.md
**Objetivos deste PR**
Me adicionar na lista de mentores
**O que foi alterado**
Inclui meus dados na lista de mentores
**Como validar**
Verificar se meu perfil esta válido
=> Me adicionando na lista de mentores @diegoleme

mentors-list.md
O principal objetivo desse PR é me adicionar como mentora colocando os meus contatos na lista.
=> Inclusão Aline Oliveira Dias como mentora

mentors-list.md
=> Add meus contatos e infos Update mentors-list.md

mentors-list.md
Adiciona Narlei Moreira como mentor iOS - Swift e Objective-C
=> Add mentor iOS Narlei Moreira

mentors-list.md
Adicionar snowflake em Bruno Couto
=> Add snowflake em Bruno Couto

mentors-list.md
=> Pushing mentor Gabriel Santos

mentors-list.md
* Adicionar Cezar Sampaio como mentor
* Adicionado Cezar Sampaio como mentor
* Validar links de contato adicionandos no mentor
=> Adicionando Cezar Sampaio como mentor

mentors-list.md
PR para adicionar os meus dados na lista de mentores
=>  Add gnuns to the mentors list 

mentors-list.md
Alteração campo de contato
telegram para ❄️ 
=> :snowflake: em Elaine Okada

mentors-list.md
Add Cayo como mentor
Adicionando Linha com informações sobre Cayo Rodrigues
Verificando file mentors-list.md
=> Add Cayo como mentor

mentors-list.md
Me adicionar a lista de mentores
Minhas informações pessoais foram adicionadas a lista de mentores(as)
Verificando file mentors-list.md
=> Me adicionando a lista de mentores

mentors-list.md
Ordenar a lista de mentores pela inatividade, ou seja, deixar por último todos os mentores que estão indisponíveis para contato
O arquivo `README.md`, na tabela de mentores
Escrevi um algoritmo em Ruby para fazer essa ordernação
```ruby
mentors_list = [
"[Matheus Melo](https://github.com/matheuscmelo) | BACK-END / PYTHON / INICIANTES EM PROGRAMAÇÃO | [Telegram](https://telegram.me/metmelo)",
"[Rafael Guerra](https://github.com/faelwar) | BACK-END/ INICIANTES EM PROGRAMAÇÃO /JAVA | [Twitter](https://twitter.com/faelwar)",
"[Cayo Rodrigues](https://www.linkedin.com/in/cayo-henrique-serra-rodrigues-a5a13337/) | BACK-END / PHP / INICIANTES EM PROGRAMAÇÃO | [Twitter](https://twitter.com/CayoHenrique08) [Telegram](https://telegram.me/cayorodrigues)",
"[Gabriel Nunes](https://multiverso.me/) | …
```
=> Sort mentors by inactivity

mentors-list.md
Deixar meu nome ativo novamente.
Retirei ❄️  do meu nome . 
Checar [template](mentor-list.template.md) 
=> Remove Claudson of the freezer

.github/mentor-guidelines.md
Trabalho em andamento (WIP)
---
Um guia para novos mentores e mentoras, assim como o guia de mentorados, e um link para este guia em nossa lista de mentores(as), assim como em nosso README.
Este documento será escrito de maneira coletiva em conjunto com mentores e mentoras que já participam do projeto, portanto este PR ficará aberto até acharmos que o documento está aceitável e bem explicado. :heart: 
Como base podemos seguir os esquemas do WeAllJS, indicados pela @cyberglot:
Mentor Guide: https://wealljs.org/rfc-mentorship-mentor
Mentee Guide: https://wealljs.org/rfc-mentorship-mentee
Porém levando para o nosso contexto, que foi discutido na reunião do dia 01/07/2018.
=> Criando guidelines (mentee e mentor)

mentors-list.md
Me transferir para a lista de mentores indisponíveis
Removi meu nome da tabela de mentores disponíveis e adicionei ao final da lista de mentores indisponíveis
=> Transfere Aline Pêgas para mentores indisponíveis

mentors-list.md
- Adicionar nome como mentora
- Mentors-list, adicionando linha com meus dados para mentoria
=> add mentor

mentors-list.md
Adiciona mentor
Inserido uma linha no topo da pilha
Validar o template
=> add Ricardo Moraleida

mentors-list.md
Me adicionando como mentor
Inserido uma linha no topo da pilha
=> Adicionando André Rodrigues

mentors-list.md
Me colocar no freezer
Adicionei :snowflake:
=> Add :snowflake: to gnuns

mentors-list.md
Fiz uma alteração no link do contato do mentor apenas para manter o padrão.
#1050
=> Correção no link do mentor

mentors-list.md
Me adiciona como mentor ativo.
Foi adicionado mais um mentor no começo da lista.
=> Adicionar um mentor

mentors-list.md
=> Voltando contato para disponível

mentors-list.md
Melhorias gerais em relação ao arquivo que representa a lista de mentores
- Corrigir a ausência de espaços entre "tipos de mentorias"
- Remover espaços desnecessários entre "tipos de mentorias"
- Url do perfil
É possível testart comparando o preview de ambos arquivos .md
=> Corrigir [ausência de espaços, espaços desnecessários, url de perfil]

mentors-list.md
Adicionar Diego Leme ao snowflake
=> Adicionar Diego Leme ao snowflake

testimonials/HidemitsuHashimoto.md
Depoimento para meu mentor.
Adicionado arquivo .md para depoimento.
=> Depoimento - Giovanni Cruz

mentors-list.md
=> Add @onhernandes

mentors-list.md
Reorganizando meu contato na lista e passando pro topo =)
=> Reorganizar

mentors-list.md
=> Add @itsmegrave

mentors-list.md
Atualizar o perfil e o foco da mentoria.
Tipos de mentoria (Badges)
Esta de acordo com o template fornecido.
=> Atualizacao de perfil

mentors-list.md
Adicionar novo mentor
Adicionado item na primeira linha ta tabela de mentores ativos
Checar se o markdown está correto :+1:
=> Add @allanbrito

mentors-list.md
=> Adicionando o mentor Thiago Galvani à lista de mentores

mentors-list.md
Adicionar mentor na lista de mentores
Foi adicionado um novo mentor na tabela de mentores
=> Adicionando o mentor Otavio Henrique à lista de mentores

mentors-list.md
Add cadastro de Mentoria Ernandes Ferreira
=> Cadastro de mentoria - Ernandes Ferreira

mentors-list.md
Adicionar Fernando Bueno Dansi a lista de mentoria
Lista de mentoria
=> Adicionando Fernando Bueno na Lista de mentoria

mentors-list.md
Me adicionei na lista de mentores.
Verificar se Alison Cassis estará presente no topo da pilha.
=> Adicionando Alison Cassis na Lista de mentoria

mentors-list.md
Remover meus dados da lista de mentores
Movi a linha com meus dados para a lista de mentores indisponíveis
=> remove onhernandes from mentors list

mentors-list.md
Remover meu nome da lista
Linha com os meus detalhes removida
=> Remove myself

mentors-list.md
Adicionar Diego Leme na lista de mentores ativos
=> Adicionar Diego Leme na lista de mentores ativos

mentors-list.md
Me adicionar na lista de mentores
=> feat: add Diogo Felix

mentors-list.md
Pausa na mentoria
foi alterado o arquivo mentors-list.md
=> Pausa mentoria

mentors-list.md
Eu estava nas duas seções da página, mas de qualquer forma estou mentorando e só consigo um por vez.
Me manter apenas no :snowflake:
Removida linha dos mentores ativos. 
Cheque que eu saí da seção de mentores ativos mas que continuo na dos :snowflake:. 
=> Deixe-me na geladeira  :snowflake:

mentors-list.md
* Me adicionar como mentor
* Coloquei meus dados na primeira linha da tabela
* Verificar se segue o padrão estipulado
=> Fernando Migliorini Tenório

mentors-list.md
- Me adicionar na lista de mentores
- Coloquei meus dados na lista
- Verificar se Lukas Pol está no topo da lista
=> add myself

mentors-list.md
Adicionar Wésley Queiroz como mentor ao projeto
Lista de mentores
Verificar se o registro na lista de mentores está de acordo com o template.
=> Add wesleycoder

mentors-list.md
Atualizar dados do Mentor Glauber Sampaio
Tipo de mentoria e contato
Novos tipos de mentoria adicionados e contato do twitter removido
=> Atualizando Tipos de Mentoria e Contato do Glauber Sampaio

mentors-list.md
Remove meu perfil (Tiago Danin), atualmente não tenho muito tempo livre para que eu possa dedicar ao processo.
Retirada do perfil Tiago Danin
=> Remove meu perfil (TiagoDanin)

mentors-list.md
Me coloca de volta como mentora disponivel.
Lista de mentores.
Verificar se o layout no markdown não está quebrado
=> Me coloca de volta como mentora disponivel

mentors-list.md
Remover meu nome como mentora disponível
Meu nome passou para a lista dos mentores indisponíveis
Verificar mentors-list.md no meu fork
=> Remove Ana Coimbra from mentors list

mentors-list.md
Mover meu nome para a lista de mentores indisponíveis
O meu nome foi removido da lista de mentores disponíveis e adicionado no topo da lista de mentores indisponíveis.
"Gustavo Straube" não está mais na lista de mentores disponíveis e apenas na lista de mentores indisponíveis.
=> Movendo meu nome para a lista de mentores indisponíveis

mentors-list.md
=> Adicionando @ingridpitta na lista

mentors-list.md
Remover Lukas Pol da lista do mentores ativos
Removido Lukas Pol da lista ativos e colocado em "congelado"
Verificando se o nome Lukas Pol não está na lista ativos, e sim na ultima linha dos "congelados"
=> remove Lukas pol the List

mentors-list.md
Tenho algumas mentorias em andamento e para evitar uma sobrecarga estou congelando o perfil.
Meu perfil foi movido para a seção "Mentores indisponíveis" e marcado com :snowflake:
=> Freezing Wésley Queiroz profile

mentors-list.md
Adicionar meu contato como mentor
=> Add LeoVitale

mentors-list.md
Objetivos deste PR
Me adicionar como Mentor disponível.
O que foi alterado
Lista de mentores disponíveis.
Como validar
Garantir que meus dados estão corretos e que meu contato é https://www.linkedin.com/in/willian-emboava-de-oliveira-20b82414b/
=> add willian emboava

mentors-list.md
Incluindo meu nome como novo mentor, atuo como Fullstack com conhecimento em ReactJs (Redux/Saga), NodeJs, .Net Core, banco de dados em geral e arquitetura de software
=> Incluindo meu nome como novo mentor

mentors-list.md
Ficar indisponível como mentor
Remoção de mentor da lista de ativos pra lista de inativo.
=> unlist grave :(

mentors-list.md
Estou me adicionando como mentora disponível
Lista de mentores disponíveis
Conferir a lista de mentores
**Feito**
=> Add Leticia Costa

mentors-list.md
Remove myself from mentors available
=> Remove myself from mentors available

mentors-list.md
Me colocar na lista de mentores disponíveis.
A lista de mentores disponíveis.
Verificar se os links adicionados estão corretos.
=> Adicionando o Tarsis de Lima como mentor

mentors-list.md
Esse PR esconde meus dados de contato, substituindo-os pelo ❄️ .
Meus dados de contato.
Se os dados foram substituídos pelo ❄️ , então está tudo certo.
=> Esconder meus dados de contato

mentors-list.md
=> Update mentors-list.md - Me readicionando à lista de mentoria

mentors-list.md
=> Matheus castiglioni

mentors-list.md
Me adicionar como Mentor disponível.
Lista de mentores disponíveis.
Garantir que meus dados estão corretos e que meu contato é https://telegram.me/luanfonceca e meu github: https://github.com/luanfonceca
=> Add luanfonceca

mentors-list.md
Estou me adicionando como mentor disponível
Conferir lista de mentores
**feito**
=> Adiciona @theGusPassos como mentor disponivel

mentors-list.md
This change was made on #1140 but apparently a merge didn't work quite well.
=> Remove biancarosa from available mentors

mentors-list.md
A Letícia Costa entrou em contato comigo por e-mail alegando não ter se cadastrado neste site. Após investigar eu descobri que o telegram informado não pertence a mentora cadastrada mas sim a outra pessoa com o mesmo nome.
=> Removendo telegram errado

mentors-list.md
=> Adiciona @vitornere como mentor disponível

mentors-list.md
Remover Lukas Pol duplicado
Removido a linha Lukas Pol da lista de mentor ativo
Verificar na lista de ativos se existe o nome Lukas Pol
=> remove Lukas Pol on the List active

mentors-list.md
=> Removendo meu contato da lista de ativos

mentors-list.md
Infelizmente nao estou tendo muito tempo para me dedicar como mentor, por enquanto esotu me retirando, no futuro talvez eu volte
=> Removing myself from the list

mentors-list.md
Me remover da lista de mentores ativos.
Lista de mentores ativos para front end.
=> Remove Leticia Dias

mentors-list.md
=> Remover Davi Busanello da lista
